name: qunova
description: "A new Phonebook app for Antripe"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # Dependency Injection
  get_it: ^9.2.1

  # Networking
  http: ^1.6.0

  # Image Caching
  cached_network_image: ^3.4.1

  # Navigation
  go_router: ^17.1.0

  # Local Persistence
  shared_preferences: ^2.5.4

  # Alphabetical ListView
  azlistview: ^2.0.0

  # Date Formatting (comes with Flutter SDK)
  intl: ^0.20.2

  # SVG Support
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  image_path: "assets/images/png/app_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/svg/

